# Eval
# These settings only apply when running eval.py (instead of ppo.py)
eval:
  episode_length: 2000
  n_parallel: 16  # Number of eval envs to be run in parallel
  training_name: launch_dummy_SAC_run  # Path to stored model, relative to Wind-RL/
  model_id: 515  # ID of model to be evaluated
  save_flow: False  # WARNING this will save HUGE amounts of data
  dummy_update: False
  initial_reset_frames: 5000  # should be 5000
  inbetween_reset_frames: 150  # number of frames to reset before we start the next eval in each env
  num_rollouts: 1  # number of times we evaluate in each env. We will get num_rollouts * n_parallel total episodes.
  use_fixed_angles: True
  fixed_angles: [0,0,0]  # only relevant if use_fixed_angles is True

# Configure hydra
hydra:
  run:
    dir: outputs
  output_subdir: hydra_logs
  
