# task and env
env:
  n_parallel: 1
  n_processors_per_env: 32
  dummy_update: False
  env_name: WindFarm
  turbines: 3
  probes_per_turbine: 25
  turbine_diameter: 126
  turbine_spacing: 7
  max_yaw_speed: 0.25
  max_yaw_angle: 40
  steps_per_frame: 50

# collector
collector:
  frame_skip: 1  # Env takes 50 time steps per update
  frames_per_batch: 200 # this is the actual number of frames we see in a batch
  max_episode_length: 1_000  # Timesteps (disregarding frame skip)
  total_frames: 50_000  # Timesteps (disregarding frame skip)

# logger
logger:
  backend: wandb
  mode: offline
  test_interval: 5_000
  num_test_episodes: 1
  test_episode_length: 1_000
  checkpoint_interval: 10
  project_name: Wind-PPO-testing
  team_name: why_are_all_the_good_names_taken_aaa
  logging_stream: stdout  # stdout to print to console or empty (None) to print to standard log file

# Optim
optim:
  lr: 1e-4
  weight_decay: 0.0
  anneal_lr: True
  load_from_checkpoint: False
  model_checkpoint_path:   # Path to checkpoint, RELATIVE to ppo/ppo.py
  model_checkpoint_id:   # ID of checkpoint

# loss
loss:
  gamma: 0.99
  mini_batch_size: 25  # must be less than frames per batch
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coef: 0.25
  entropy_coef: 0.0
  loss_critic_type: l2
