# environment and task
env:
  n_parallel: 32
  n_processors_per_env: 128
  dummy_update: False
  env_name: WindFarm
  turbines: 3
  probes_per_turbine: 77
  flow_field_directions: ['ux', 'uz']  # we will use these components of the flow field for each probe
  turbine_diameter: 126
  turbine_height: 90
  turbine_spacing: 5
  turbine_spacing_z: 7
  max_yaw_speed: 1.0
  max_yaw_angle: 40
  steps_per_frame: 50
  reset_frames: 150
  # reset_frames: 3000  # combined for eval
  initial_reset_frames: 5000
  frame_stack: 1  # Number of frames to be stacked as agent input
  reward_average_steps: 1  # Number of frames over which to average the reward
  penalty_scale: 0.5
  penalty_exp: 26
  velocity_penalty_scale: 0.0
  difference_penalty_scale: 0.0
  random_reset: False  # If True, at each reset angles will be chosen randomly
  initial_angles: [0, 0, 0]
  precursor_root: "/work/e01/e01/klop1/wind/Wind-RL/Solver/ADM"

# Multi-agent or single-agent training?
multi_agent:
  use: False

# collector
collector:
  total_frames: 500_000 # 1_000_000
  init_random_frames: 32_000
  max_episode_length: 500  # Timesteps
  frames_per_batch: 1024
  device: cpu

# replay buffer
replay_buffer:
  size: ${collector.total_frames}
  prb: False # use prioritized experience replay; the original TQC paper does not prioritized replay 

# optim
optim:
  gamma: 0.99
  lr: 3.0e-6
  entropy_lr: 3.0e-4
  step_mult: 1
  weight_decay: 0.0
  batch_size: 256
  target_update_polyak: 0.995
  alpha_init: 1.0
  adam_eps: 1.0e-8

# network
network:
  actor_hidden_depth: 2
  actor_hidden_size: 256
  critic_hidden_depth: 2
  critic_hidden_size: 256
  default_policy_scale: 1.0
  scale_lb: 0.1
  device: cpu

# logging
logger:
  logging_stream: stdout  # stdout to print to console or empty (None) to print to standard log file

# Configure hydra
hydra:
  run:
    dir: outputs
  output_subdir: hydra_logs

# Settings for checkpointing
checkpoint:
  checkpoint_interval: 50
  load_from_checkpoint: False
  model_checkpoint_path: ./training_sac_no_mult/sac/checkpoints   # Path to checkpoint, RELATIVE to Wind-RL/
  model_checkpoint_id: 410624  # ID of checkpoint
  save_replay_buffer: True  # only save the full replay buffer if this is True
